version: '3.4'

services:
  proxy:
    image: proxy
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - proxy
